# Generated by Django 5.2.6 on 2025-09-16 01:50

import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Contenido del comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/posts_images/', verbose_name='Imagen')),
                ('title', models.TextField(max_length=500, verbose_name='Titulo')),
                ('content', prose.fields.RichTextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tecnologia', 'Tecnología'), ('software', 'Software'), ('ia', 'Inteligencia Artificial'), ('desarrollo_web', 'Desarrollo Web'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('blockchain', 'Blockchain'), ('BTC', 'Bitcoin')], max_length=20, unique=True)),
            ],
        ),
    ]
