# Generated by Django 5.1.3 on 2025-02-19 20:44

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=prose.fields.RichTextField(),
        ),
    ]
