# Generated by Django 5.1.3 on 2025-02-25 23:24

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=prose.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
