# Generated by Django 5.1.3 on 2025-11-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('software', 'Software'), ('ia', 'Inteligencia Artificial'), ('desarrollo_web', 'Desarrollo Web'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('blockchain', 'Blockchain'), ('BTC', 'Bitcoin'), ('innovacion', 'Innovación'), ('productividad', 'Productividad'), ('emprendimiento', 'Emprendimiento'), ('creatividad', 'Creatividad'), ('minimalismo', 'Minimalismo'), ('futuro', 'Futuro')], max_length=20, unique=True),
        ),
    ]
