# Generated by Django 5.1.3 on 2025-03-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_password_change',
            field=models.DateField(auto_now=True, verbose_name='Último cambio de contraseña'),
        ),
    ]
