# Generated by Django 5.1.3 on 2025-03-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_last_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último cambio de contraseña'),
        ),
    ]
