# Generated by Django 5.1.3 on 2025-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Perfil privado'),
        ),
    ]
