# Generated by Django 5.1.3 on 2025-11-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_follow_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuarios'},
        ),
    ]
