# Generated by Django 5.1.3 on 2025-03-14 01:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Sala de Chat', 'verbose_name_plural': 'Salas de Chat'},
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
