# Generated by Django 5.1.3 on 2025-03-21 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options_alter_chatroom_id'),
        ('profiles', '0005_userprofile_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatRoom',
            fields=[
                ('chatroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.chatroom')),
                ('description', models.TextField(max_length=500)),
                ('admins', models.ManyToManyField(to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Grupo de Chat',
                'verbose_name_plural': 'Grupos de Chat',
            },
            bases=('chat.chatroom',),
        ),
    ]
