# Generated by Django 5.1.3 on 2025-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagen de grupo'),
        ),
    ]
