# Generated by Django 5.1.3 on 2025-11-12 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupchatroom_image'),
        ('profiles', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='profiles.userprofile'),
        ),
    ]
