# Generated by Django 5.1.3 on 2025-11-12 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupchatroom_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
