# Generated by Django 5.1.3 on 2025-11-12 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_groupchatroom_created_at'),
        ('profiles', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='profiles.userprofile'),
        ),
    ]
