# Generated by Django 5.1.3 on 2025-11-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_groupchatroom_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
