# Generated by Django 5.1.3 on 2025-04-22 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_post_likelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
